# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'SkylinkSample' do
pod 'SKYLINK', :git => 'https://github.com/Temasys/SKYLINK-iOS.git', :tag => ‘1.0.11’
pod "UIAlertView-Blocks"
end
